import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function PrivacyPolicyPage() {
    return (
        <div className="flex flex-col min-h-screen bg-background">
            {/* Header */}
            <header className="flex items-center gap-4 px-6 py-4 border-b bg-background sticky top-0 z-10">
                <Link
                    to="/auth/login"
                    className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
                >
                    <ArrowLeft className="h-4 w-4" />
                    Back to Login
                </Link>
                <h1 className="text-lg font-semibold text-foreground">Privacy Policy</h1>
            </header>

            {/* Content */}
            <div className="flex-1 overflow-y-auto">
                <div className="max-w-3xl mx-auto px-6 py-10 text-foreground">
                    <h1 className="text-3xl font-bold mb-2">GC Analytics Privacy Policy</h1>
                    <p className="text-muted-foreground mb-8">Effective date: 25 February 2026</p>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">1. Overview</h2>
                        <p className="leading-relaxed">
                            This Privacy Policy explains how Greycats Tech LLP collects, uses, shares, and
                            protects personal and account data when you use GC Analytics at{" "}
                            <a href="https://analytics.greycats.tech" className="text-primary underline" target="_blank" rel="noopener noreferrer">
                                https://analytics.greycats.tech
                            </a>{" "}
                            and related APIs and integrations.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">2. Data Controller and Contact</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Controller</strong> – Greycats Tech LLP.</li>
                            <li>
                                <strong>Contact</strong> –{" "}
                                <a href="mailto:info@greycats.tech" className="text-primary underline">info@greycats.tech</a>{" "}
                                or{" "}
                                <Link to="/contact" className="text-primary underline">
                                    https://analytics.greycats.tech/contact
                                </Link>{" "}
                                for privacy inquiries and data requests.
                            </li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">3. Data We Collect</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Account Information</strong> – name, email, organization, billing details.</li>
                            <li><strong>Authentication Data</strong> – OAuth tokens, API keys, and metadata required to access connected third‑party accounts.</li>
                            <li><strong>Connected Account Data</strong> – social media metrics, Google Analytics data, Google Ads data, posts, comments, impressions, clicks, campaign metadata, and other analytics data you authorize us to access.</li>
                            <li><strong>Usage Data</strong> – logs, IP address, device and browser information, timestamps, and feature usage.</li>
                            <li><strong>Reports and Derived Data</strong> – aggregated metrics, dashboards, and analytics outputs generated by the Service.</li>
                            <li><strong>Support Data</strong> – communications with support, diagnostics, and error reports.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">4. How We Collect Data</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Directly from You</strong> when you register, configure integrations, or contact support.</li>
                            <li><strong>From Third‑Party Platforms</strong> when you connect accounts via OAuth or APIs.</li>
                            <li><strong>Automatically</strong> through cookies and similar technologies when you use the Service.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">5. Purposes for Processing</h2>
                        <p className="mb-3 leading-relaxed">We process data to:</p>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li>Provide, operate, and maintain the Service.</li>
                            <li>Generate analytics, dashboards, and scheduled reports.</li>
                            <li>Authenticate and authorize access to third‑party accounts.</li>
                            <li>Improve and personalize the Service.</li>
                            <li>Communicate with you about your Account and updates.</li>
                            <li>Detect, prevent, and respond to security incidents and abuse.</li>
                            <li>Comply with legal obligations.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">6. Legal Bases for Processing</h2>
                        <p className="mb-3 leading-relaxed">Where applicable, we rely on:</p>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Performance of a contract</strong> to provide the Service.</li>
                            <li><strong>Consent</strong> for optional features such as marketing communications and certain cookies.</li>
                            <li><strong>Legitimate interests</strong> for security, fraud prevention, and product improvement, balanced against your rights.</li>
                            <li><strong>Legal obligations</strong> when required by law.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">7. Sharing and Disclosure</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Service Providers</strong> – We share data with processors who perform services on our behalf, such as hosting, analytics, email, and payment processors.</li>
                            <li><strong>Third‑Party Platforms</strong> – Data is accessed from and may be shared with third‑party platforms only as authorized by you.</li>
                            <li><strong>Legal Requirements</strong> – We may disclose data to comply with legal obligations or to protect rights and safety.</li>
                            <li><strong>Business Transfers</strong> – In the event of a merger, acquisition, or sale, Client Data may be transferred subject to confidentiality protections.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">8. Data Retention</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Account Data</strong> – retained while your Account is active and for 2 years after account closure unless otherwise required by law.</li>
                            <li><strong>Connected Account Data and Reports</strong> – retained according to your settings and our retention schedule; default retention is 1 year for raw logs and 2 years for aggregated reports.</li>
                            <li><strong>Backups</strong> – retained for up to 90 days.</li>
                            <li><strong>Anonymized Data</strong> – aggregated or anonymized data may be retained indefinitely for product improvement and benchmarking.</li>
                            <li><strong>Requests</strong> – Specific retention exceptions and exact periods are available on request via{" "}
                                <a href="mailto:info@greycats.tech" className="text-primary underline">info@greycats.tech</a>.
                            </li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">9. Security</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Measures</strong> – We implement administrative, technical, and physical safeguards such as encryption in transit, access controls, and regular security assessments.</li>
                            <li><strong>Incident Response</strong> – We maintain an incident response plan and will notify affected users and authorities as required by applicable law.</li>
                            <li><strong>No Absolute Security</strong> – No system is completely secure; we cannot guarantee absolute protection but will respond to incidents in accordance with applicable law.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">10. Cookies and Tracking Technologies</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Essential Cookies</strong> – required for authentication and core functionality.</li>
                            <li><strong>Performance Cookies</strong> – to analyze usage and improve the Service.</li>
                            <li><strong>Optional Cookies</strong> – for analytics and marketing; you can manage cookie preferences in your browser or Account settings.</li>
                            <li>
                                <strong>Cookie Policy</strong> – a full cookie table and opt‑out instructions are available at{" "}
                                <Link to="/cookies" className="text-primary underline">
                                    https://analytics.greycats.tech/cookies
                                </Link>.
                            </li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">11. Your Rights and Choices</h2>
                        <p className="mb-3 leading-relaxed">Depending on your jurisdiction, you may have rights to:</p>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li>Access the personal data we hold about you.</li>
                            <li>Rectify inaccurate or incomplete data.</li>
                            <li>Delete or request erasure of your data.</li>
                            <li>Restrict or Object to certain processing.</li>
                            <li>Data Portability to receive a copy of your data in a structured format.</li>
                        </ul>
                        <p className="mt-3 leading-relaxed">
                            To exercise rights, contact{" "}
                            <a href="mailto:info@greycats.tech" className="text-primary underline">info@greycats.tech</a>.
                            We may require verification and will respond within applicable legal timeframes.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">12. International Transfers</h2>
                        <p className="leading-relaxed">
                            Data may be processed or stored in jurisdictions outside your country. We use
                            appropriate safeguards such as standard contractual clauses or other lawful
                            mechanisms to protect transfers.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">13. Children</h2>
                        <p className="leading-relaxed">
                            The Service is not directed to children under 13. We do not knowingly collect personal
                            data from children. If we learn we have collected data from a child without parental
                            consent, we will take steps to delete it.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">14. Third‑Party Links and Services</h2>
                        <p className="leading-relaxed">
                            The Service may link to third‑party websites and services. This Privacy Policy does not
                            apply to third parties. Review their privacy policies before providing data.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">15. Data Processing Addendum and Subprocessors</h2>
                        <ul className="list-disc pl-6 space-y-2 leading-relaxed">
                            <li><strong>Subprocessors</strong> – We maintain a list of subprocessors (hosting, analytics, payment, email) available on request.</li>
                            <li><strong>DPA</strong> – Enterprise customers may request a Data Processing Addendum that includes standard contractual clauses and security commitments.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">16. Changes to This Policy</h2>
                        <p className="leading-relaxed">
                            We may update this Privacy Policy. We will post the revised policy with an updated
                            effective date at{" "}
                            <Link to="/privacy-policy" className="text-primary underline">
                                https://analytics.greycats.tech/privacy
                            </Link>.
                            Continued use after changes constitutes acceptance.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-xl font-semibold mb-3">17. Contact Information</h2>
                        <p className="leading-relaxed">
                            For privacy questions, data requests, or complaints contact{" "}
                            <a href="mailto:info@greycats.tech" className="text-primary underline">info@greycats.tech</a>{" "}
                            or visit{" "}
                            <Link to="/contact" className="text-primary underline">
                                https://analytics.greycats.tech/contact
                            </Link>.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
